baseURL = "https://bjxihi.com/"
languageCode = "zh-cn"
title = "Xihi 的博客"
theme = "PaperMod" 
defaultContentLanguage = "zh"

[params]
  env = "production"
  author = "Xihi"
  description = "个人博客"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1